spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.springframework: error
    org.hibernate: error
    org.hibernate.SQL:
      SQL: DEBUG
  file:
    name: logs/logfile.log


